Repository longndhe140970/swp391_G5, pull requests merged in 2024-06, with the labels that each got.

#56 Fix cart be
  README.md
  baseData.sql
  be/pom.xml
  be/src/main/java/com/example/onlineshop/controller/CartController.java
  be/src/main/java/com/example/onlineshop/repository/CityResponsitory.java
  be/src/main/java/com/example/onlineshop/repository/CustomerResponsitory.java
  be/src/main/resources/application.properties
  fe/package-lock.json
  fe/package.json
  fe/src/asset/avatar.jpg
  fe/src/components/Button/Button.js
  fe/src/components/CardBook/CardBook.js
  fe/src/components/Input/InputField.js
  fe/src/components/Input/InputFieldUpload.js
  fe/src/components/Table/Table.js
  fe/src/layout/MainLayout.js
  fe/src/pages/Cart/Components/DeleteButton.js
  fe/src/pages/Cart/Components/QuantityButton.js
  fe/src/pages/Cart/Components/tableConfig.js
  fe/src/pages/Cart/hooks/useOrderHooks.js
  fe/src/pages/Cart/index.js
  fe/src/pages/Login/Components/LoginForm.js
  fe/src/pages/Profile.js
  fe/src/pages/SearchBook/index.js
  fe/src/routes/routes.js
  fe/src/services/constant.js
  fe/src/services/customAxios.js
  fe/src/utils/constants.js
  fe/src/utils/utils.js
Labels: fixed

#58 #34 #32 Signup-FE Home-FE
  be/pom.xml
  fe/src/pages/Home.js
  fe/src/pages/SignUpPage.js
  fe/src/routes/routes.js
  fe/src/services/constant.js
Labels: task, closed

#59 #39 BookDetail-FE
  fe/src/components/ReadMore.js
  fe/src/pages/BookDetail/BookDetailPage.js
  fe/src/pages/BookDetail/Components/BookDetailComponent.js
  fe/src/routes/routes.js
Labels: task, closed

#61 Fe many page
  be/src/main/java/com/example/onlineshop/controller/CartController.java
  be/src/main/java/com/example/onlineshop/repository/CityResponsitory.java
  be/src/main/java/com/example/onlineshop/repository/CustomerResponsitory.java
  be/src/main/resources/application.properties
  fe/package-lock.json
  fe/package.json
  fe/src/components/Button/ButtonV2.js
  fe/src/components/TableV2/Components/SearchData.js
  fe/src/components/TableV2/index.js
  fe/src/components/Title/index.js
  fe/src/layout/Header.js
  fe/src/layout/ManagerLayout.js
  fe/src/layout/ManagerLayout/Components/SideBar.js
  fe/src/layout/ManagerLayout/ManagerLayout.js
  fe/src/pages/AdminAccount/Components/ActionButton.js
  fe/src/pages/AdminAccount/config/tableConfig.js
  fe/src/pages/AdminAccount/index.js
  fe/src/pages/Dashboard/index.js
  fe/src/pages/Login/Components/LoginForm.js
  fe/src/pages/Login/LoginPage.js
  fe/src/pages/employee/AuthorPage/config/tableConfig.js
  fe/src/pages/employee/AuthorPage/index.js
  fe/src/pages/employee/BookPage/config/tableConfig.js
  fe/src/pages/employee/BookPage/index.js
  fe/src/pages/employee/CategoryPage/config/tableConfig.js
  fe/src/pages/employee/CategoryPage/index.js
  fe/src/pages/employee/OrderPage/config/tableConfig.js
  fe/src/pages/employee/OrderPage/index.js
  fe/src/pages/employee/PublisherPage/config/tableConfig.js
  fe/src/pages/employee/PublisherPage/index.js
  fe/src/routes/MenuAdmin.js
  fe/src/routes/MenuEmpl.js
  fe/src/routes/routes.js
  fe/src/utils/utils.js
Labels: fixed

#62 Add favorite list feature
  be/pom.xml
  be/src/main/java/com/example/onlineshop/controller/FavoriteController.java
  be/src/main/java/com/example/onlineshop/dto/BookCardDto.java
  be/src/main/java/com/example/onlineshop/payload/request/FavoriteRequest.java
  be/src/main/java/com/example/onlineshop/repository/FavoriteRepository.java
  be/src/main/java/com/example/onlineshop/service/FavoriteService.java
  be/src/main/java/com/example/onlineshop/service/impl/FavoriteServiceImpl.java
  fe/src/components/CardBook/CardBook.js
  fe/src/layout/Header.js
  fe/src/pages/BookDetail/Components/BookDetailComponent.js
  fe/src/pages/Favorite/Components/RemoveButton.js
  fe/src/pages/Favorite/index.js
  fe/src/pages/History/index.js
  fe/src/pages/Login/LoginPage.js
  fe/src/pages/employee/AuthorPage/config/tableConfig.js
  fe/src/pages/employee/AuthorPage/index.js
  fe/src/pages/employee/CategoryPage/config/tableConfig.js
  fe/src/pages/employee/CategoryPage/index.js
  fe/src/pages/employee/OrderPage/config/tableConfig.js
  fe/src/pages/employee/OrderPage/index.js
  fe/src/pages/employee/PublisherPage/config/tableConfig.js
  fe/src/pages/employee/PublisherPage/index.js
  fe/src/routes/routes.js
  fe/src/services/constant.js
Labels: task

#64 #15 update text_area
  fe/package-lock.json
  fe/package.json
  fe/src/components/ReadMore.js
  fe/src/components/Section/index.js
  fe/src/components/TextArea/index.js
  fe/src/layout/ManagerLayout/Components/SideBar.js
  fe/src/layout/ManagerLayout/ManagerLayout.js
  fe/src/pages/BookDetail/BookDetailPage.js
  fe/src/pages/BookDetail/Components/BookDetailComponent.js
  fe/src/pages/SignUpPage.js
  fe/src/routes/routes.js
Labels: task

#66 #65 empl_create_order
  fe/src/pages/employee/OrderAdd/components/InforBook.js
  fe/src/pages/employee/OrderAdd/components/InforForm.js
  fe/src/pages/employee/OrderAdd/config/tableConfig.js
  fe/src/pages/employee/OrderAdd/index.js
  fe/src/pages/employee/OrderPage/index.js
  fe/src/routes/MenuEmpl.js
  fe/src/routes/routes.js
  fe/src/services/constant.js
  fe/src/utils/constants.js
  fe/src/utils/utils.js
Labels: task

#67 Fix conflict
  be/src/main/java/com/example/onlineshop/controller/FavoriteController.java
  be/src/main/java/com/example/onlineshop/dto/BookCardDto.java
  be/src/main/java/com/example/onlineshop/payload/request/FavoriteRequest.java
  be/src/main/java/com/example/onlineshop/repository/FavoriteRepository.java
  be/src/main/java/com/example/onlineshop/service/FavoriteService.java
  be/src/main/java/com/example/onlineshop/service/impl/FavoriteServiceImpl.java
  fe/package-lock.json
  fe/package.json
  fe/src/components/Button/ButtonV2.js
  fe/src/components/CardBook/CardBook.js
  fe/src/components/ReadMore.js
  fe/src/components/Section/index.js
  fe/src/components/TableV2/Components/SearchData.js
  fe/src/components/TableV2/index.js
  fe/src/components/TextArea/index.js
  fe/src/components/Title/index.js
  fe/src/layout/Header.js
  fe/src/layout/ManagerLayout.js
  fe/src/layout/ManagerLayout/Components/SideBar.js
  fe/src/layout/ManagerLayout/ManagerLayout.js
  fe/src/pages/AdminAccount/Components/ActionButton.js
  fe/src/pages/AdminAccount/config/tableConfig.js
  fe/src/pages/AdminAccount/index.js
  fe/src/pages/BookDetail/BookDetailPage.js
  fe/src/pages/BookDetail/Components/BookDetailComponent.js
  fe/src/pages/Dashboard/index.js
  fe/src/pages/Favorite/Components/RemoveButton.js
  fe/src/pages/Favorite/index.js
  fe/src/pages/History/index.js
  fe/src/pages/Home.js
  fe/src/pages/Login/Components/LoginForm.js
  fe/src/pages/Login/LoginPage.js
  fe/src/pages/SignUpPage.js
  fe/src/pages/employee/AuthorPage/config/tableConfig.js
  fe/src/pages/employee/AuthorPage/index.js
  fe/src/pages/employee/BookPage/config/tableConfig.js
  fe/src/pages/employee/BookPage/index.js
  fe/src/pages/employee/CategoryPage/config/tableConfig.js
  fe/src/pages/employee/CategoryPage/index.js
  fe/src/pages/employee/OrderAdd/components/InforBook.js
  fe/src/pages/employee/OrderAdd/components/InforForm.js
  fe/src/pages/employee/OrderAdd/config/tableConfig.js
  fe/src/pages/employee/OrderAdd/index.js
  fe/src/pages/employee/OrderPage/config/tableConfig.js
  fe/src/pages/employee/OrderPage/index.js
  fe/src/pages/employee/PublisherPage/config/tableConfig.js
  fe/src/pages/employee/PublisherPage/index.js
  fe/src/routes/MenuAdmin.js
  fe/src/routes/MenuEmpl.js
  fe/src/routes/routes.js
  fe/src/services/constant.js
  fe/src/utils/constants.js
  fe/src/utils/utils.js
Labels: bug, fixed

#69 #68 done
  be/src/main/java/com/example/onlineshop/configuration/services/UserDetailsImpl.java
  be/src/main/java/com/example/onlineshop/constant/ERole.java
  be/src/main/java/com/example/onlineshop/controller/BookController.java
  be/src/main/java/com/example/onlineshop/entity/User.java
  be/src/main/java/com/example/onlineshop/entity/UserDetail.java
  be/src/main/java/com/example/onlineshop/payload/request/CreateOrderRequest.java
  be/src/main/java/com/example/onlineshop/repository/BookRepository.java
  be/src/main/java/com/example/onlineshop/repository/UserRepository.java
  be/src/main/java/com/example/onlineshop/service/BookService.java
  be/src/main/java/com/example/onlineshop/service/impl/BookServiceImpl.java
  be/src/main/java/com/example/onlineshop/service/impl/OrderServiceImpl.java
Labels: task

#73 #72 upload image
  be/.gitignore
  be/pom.xml
  be/src/main/java/com/example/onlineshop/configuration/WebSecurityConfig.java
  be/src/main/java/com/example/onlineshop/configuration/cloudinary/CloudinaryConfig.java
  be/src/main/java/com/example/onlineshop/controller/ImageController.java
  be/src/main/java/com/example/onlineshop/repository/UserRepository.java
  be/src/main/java/com/example/onlineshop/service/ImageService.java
  be/src/main/java/com/example/onlineshop/service/impl/ImageServiceImpl.java
Labels: task, closed

#76 Book rating
  be/src/main/java/com/example/onlineshop/controller/BookController.java
  be/src/main/java/com/example/onlineshop/controller/FavoriteController.java
  be/src/main/java/com/example/onlineshop/entity/Book.java
  be/src/main/java/com/example/onlineshop/entity/Rating.java
  be/src/main/java/com/example/onlineshop/entity/User.java
  be/src/main/java/com/example/onlineshop/payload/request/BookRequest.java
  be/src/main/java/com/example/onlineshop/payload/request/RatingRequest.java
  be/src/main/java/com/example/onlineshop/repository/OrderItemRepository.java
  be/src/main/java/com/example/onlineshop/repository/RatingRepository.java
  be/src/main/java/com/example/onlineshop/repository/UserRepository.java
  be/src/main/java/com/example/onlineshop/service/BookService.java
  be/src/main/java/com/example/onlineshop/service/impl/BookServiceImpl.java
  be/src/main/resources/application.properties
  fe/package-lock.json
  fe/src/components/CardBook/CardBook.js
  fe/src/components/Select/index.js
  fe/src/components/TextArea/index.js
  fe/src/layout/Header.js
  fe/src/pages/BookDetail/BookDetailPage.js
  fe/src/pages/BookDetail/Components/BookDetailComponent.js
  fe/src/pages/employee/AddBookPage/index.js
  fe/src/pages/employee/BookPage/index.js
  fe/src/routes/routes.js
  fe/src/services/constant.js
Labels: task

#78 fixxx
  .gitignore
  be/src/main/java/com/example/onlineshop/controller/BookController.java
  be/src/main/java/com/example/onlineshop/controller/FavoriteController.java
  be/src/main/java/com/example/onlineshop/entity/Book.java
  be/src/main/java/com/example/onlineshop/entity/Rating.java
  be/src/main/java/com/example/onlineshop/entity/User.java
  be/src/main/java/com/example/onlineshop/payload/request/BookRequest.java
  be/src/main/java/com/example/onlineshop/payload/request/RatingRequest.java
  be/src/main/java/com/example/onlineshop/repository/OrderItemRepository.java
  be/src/main/java/com/example/onlineshop/repository/RatingRepository.java
  be/src/main/java/com/example/onlineshop/repository/UserRepository.java
  be/src/main/java/com/example/onlineshop/service/BookService.java
  be/src/main/java/com/example/onlineshop/service/impl/BookServiceImpl.java
  be/src/main/java/com/example/onlineshop/service/impl/CartItemServiceImpl.java
  be/src/main/resources/application.properties
  fe/package-lock.json
  fe/package.json
  fe/src/components/CardBook/CardBook.js
  fe/src/components/Select/index.js
  fe/src/components/TextArea/index.js
  fe/src/layout/Header.js
  fe/src/layout/ManagerLayout/Components/SideBar.js
  fe/src/pages/BookDetail/BookDetailPage.js
  fe/src/pages/BookDetail/Components/BookDetailComponent.js
  fe/src/pages/History/index.js
  fe/src/pages/Home.js
  fe/src/pages/SearchBook/Components/ContentSide.js
  fe/src/pages/SearchBook/Components/MenuSide.js
  fe/src/pages/SearchBook/index.js
  fe/src/pages/SignUpPage.js
  fe/src/pages/employee/AddBookPage/index.js
  fe/src/pages/employee/AddPublisherPage/index.js
  fe/src/pages/employee/BookPage/index.js
  fe/src/pages/employee/OrderAdd/components/InforBook.js
  fe/src/pages/employee/OrderAdd/config/tableConfig.js
  fe/src/routes/MenuAdmin.js
  fe/src/routes/MenuEmpl.js
  fe/src/routes/routes.js
  fe/src/services/constant.js
Labels: bug, fixed, closed

#79 Many feature
  be/.gitignore
  be/pom.xml
  be/src/main/java/com/example/onlineshop/configuration/WebSecurityConfig.java
  be/src/main/java/com/example/onlineshop/configuration/cloudinary/CloudinaryConfig.java
  be/src/main/java/com/example/onlineshop/controller/AuthorController.java
  be/src/main/java/com/example/onlineshop/controller/ImageController.java
  be/src/main/java/com/example/onlineshop/payload/request/AuthorRequest.java
  be/src/main/java/com/example/onlineshop/repository/AuthorRepository.java
  be/src/main/java/com/example/onlineshop/repository/UserRepository.java
  be/src/main/java/com/example/onlineshop/service/AuthorService.java
  be/src/main/java/com/example/onlineshop/service/ImageService.java
  be/src/main/java/com/example/onlineshop/service/impl/AuthorServiceImpl.java
  be/src/main/java/com/example/onlineshop/service/impl/BookServiceImpl.java
  be/src/main/java/com/example/onlineshop/service/impl/ImageServiceImpl.java
  fe/src/App.css
  fe/src/components/CardBook/CardBook.js
  fe/src/components/Slide/index.js
  fe/src/index.css
  fe/src/layout/Header.js
  fe/src/layout/ManagerLayout/Components/SideBar.js
  fe/src/pages/AdminAccount/Components/ActionButton.js
  fe/src/pages/AdminAccount/config/tableConfig.js
  fe/src/pages/AdminAccount/index.js
  fe/src/pages/BookDetail/BookDetailPage.js
  fe/src/pages/BookDetail/Components/BookDetailComponent.js
  fe/src/pages/Favorite/Components/RemoveButton.js
  fe/src/pages/Favorite/index.js
  fe/src/pages/Home.js
  fe/src/pages/Login/LoginPage.js
  fe/src/pages/SearchBook/Components/ContentSide.js
  fe/src/pages/Signin.js
  fe/src/pages/employee/AuthorAdd/api/index.js
  fe/src/pages/employee/AuthorAdd/index.js
  fe/src/pages/employee/AuthorPage/config/tableConfig.js
  fe/src/pages/employee/AuthorPage/index.js
  fe/src/pages/employee/BookPage/config/tableConfig.js
  fe/src/pages/employee/BookPage/index.js
  fe/src/pages/employee/CategoryAdd/api/index.js
  fe/src/pages/employee/CategoryAdd/index.js
  fe/src/pages/employee/CategoryPage/index.js
  fe/src/pages/employee/OrderAdd/index.js
  fe/src/pages/employee/OrderPage/config/tableConfig.js
  fe/src/pages/employee/OrderPage/index.js
  fe/src/pages/employee/PublisherAdd/api/index.js
  fe/src/pages/employee/PublisherAdd/index.js
  fe/src/pages/employee/PublisherPage/index.js
  fe/src/routes/MenuAdmin.js
  fe/src/routes/MenuEmpl.js
  fe/src/routes/routes.js
  fe/src/services/constant.js
  fe/src/services/customAxios.js
  fe/src/utils/utils.js
Labels: fixed, task
